"""add embedding to chunks

Revision ID: 5d11cc9a4109
Revises: b6115f833145
Create Date: 2026-04-09 17:29:26.618799

"""
from typing import Sequence, Union
import pgvector.sqlalchemy.vector                                                                                   

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d11cc9a4109'
down_revision: Union[str, Sequence[str], None] = 'b6115f833145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
